config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  get 'projects/show'

  get 'projects/create'

  get 'projects/update'

  get 'projects/destroy'

  get 'dashboard', to: 'timelist#dashboard'

  root 'static_pages#home'
  get '/timelist', to: 'static_pages#timelist'
  get '/drivebook', to: 'static_pages#drivebook'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users, only: [:show, :index, :destroy, :create, :update]
  resources :clients, only: [:show, :index, :destroy, :create, :update]
  resources :projects, only: [:show, :index, :destroy, :create, :update]
  resources :offers, only: [:show, :index, :destroy, :create, :update]
  resources :offer_reminders, only: [:create, :destroy, :update]
  resources :contact_people, only: [:create, :destroy, :update]
  resources :notifications, only: [:show]
  resources :timelist_records, only: [:create, :destroy, :update], controller: :timelist
  resources :no_work_records, only: [:create, :destroy, :update]
  resources :work_records, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer_reminder.rb
class OfferReminder < ApplicationRecord
  belongs_to :offer
  after_create :build_notification
  after_update :update_notification
  
  validates :message, presence: true
  validates :date, presence: true
  validates :offer_id, presence: true
  
  private 
    def build_notification
      notification = Notification.new(icon: "bell-o",
                                           title: "Reminder",
                                           content: self.message,
                                           user_id: self.offer.user.id,
                                           date: self.date,
                                           content_id: self.offer.id,
                                           content_type: "offer")
      notification.save
    end
    def update_notification
      if notification = Notification.unscoped.find_by(title: "Reminder", content_type: "offer", content_id: self.id)
        self.date >= Date.today ? seen = false : seen = true
        notification.update_attributes(content: self.message,
                                       user_id: self.offer.user.id,
                                       date: self.date,
                                       seen: seen)
      end
    end
  
  
end

app/controllers/offer_reminders_controller.rb
class OfferRemindersController < ApplicationController
    
    before_action :only_logged_in
    before_action :only_admin
    
    def create
        @offer = Offer.find(params[:offer_reminder][:offer_id])
        @newReminder = @offer.reminders.build(reminder_params)
        if @newReminder.save
            flash[:success] = "Reminder created!"
            redirect_to @offer
        else
            @offer = Offer.find(params[:offer_reminder][:offer_id])
            @admins = User.where(admin: true)
            @clients = Client.order(name: :asc)
            @projects = Project.order(name: :asc)
            @newContact = ContactPerson.new
            render 'offers/show'
        end
    end
    
    def destroy
        @reminder = OfferReminder.find(params[:id])
        if @reminder.update_attribute(:deleted, true)
            flash[:success] = "Reminder deleted"
            redirect_to @reminder.offer
        else
           flash[:error] = "Something went wrong"
           redirect_to @reminder.offer
        end
    end
    
    private
        def reminder_params
           params.require(:offer_reminder).permit(:message, :date, :email, :offer_id) 
        end
end

app/helpers/offer_reminders_helper.rb
module OfferRemindersHelper
end

app/views/offer_reminders/_add_reminder_modal.html.erb
<!-- Show modal on load if adding failed -->
<% if @newReminder.errors.any? %> 
<script> $(document).ready(function(){ 
    $("#addReminderModal").modal("show"); });
</script>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    $('#offer_reminder_date').datepicker({
      format: "dd/mm/yyyy",
      autoclose: true
      });
  });
</script>

<div id="addReminderModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Adding new reminder</h4>
      </div>
      <%= form_for @newReminder do |f| %>
      <div class="modal-body">
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.hidden_field :offer_id, value: @offer.id %>
            
            <%= f.label :message %>
            <%= f.text_area :message, class: "form-control" %>
                         
            <%= f.label :date %>
            <%= f.text_field :date, class: "form-control", placeholder: "dd/mm/yyyy" %>
            <br/>
            <%= f.check_box :email %> <%= f.label :email, "Send me email" %>
            
      </div>
      <div class="modal-footer">
            <%= f.submit "Add reminder", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/offer_reminders/_offer_reminder.html.erb
<div class="alert alert-info reminder">
    <div class="pull-right">
        <span class="reminder-date">
            <%= offer_reminder.date %></i>
        </span>
        <div class="dropdown" style="display: inline; cursor: pointer;">
          <a class="dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-cog" aria-hidden="true"></i></a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to 'Delete', offer_reminder_path(offer_reminder),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>    
            </li>
            <li><a href="#">Dismiss</a></li>
          </ul>
        </div>
    </div>
    
    <strong><i class="fa fa-bell-o" aria-hidden="true"></i> Reminder </strong>
    <hr>
    <span><%= offer_reminder.message %></span>
</div>