config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  get 'projects/show'

  get 'projects/create'

  get 'projects/update'

  get 'projects/destroy'

  get 'dashboard', to: 'timelist#dashboard'

  root 'static_pages#home'
  get '/timelist', to: 'static_pages#timelist'
  get '/drivebook', to: 'static_pages#drivebook'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users, only: [:show, :index, :destroy, :create, :update]
  resources :clients, only: [:show, :index, :destroy, :create, :update]
  resources :projects, only: [:show, :index, :destroy, :create, :update]
  resources :offers, only: [:show, :index, :destroy, :create, :update]
  resources :offer_reminders, only: [:create, :destroy, :update]
  resources :contact_people, only: [:create, :destroy, :update]
  resources :notifications, only: [:show]
  resources :timelist_records, only: [:create, :destroy, :update], controller: :timelist
  resources :no_work_records, only: [:create, :destroy, :update]
  resources :work_records, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    has_many :offers
    has_many :notifications
    has_many :work_records
    has_many :no_work_records
    has_many :projects
    
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
                      length: { maximum: 255 }, 
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: {case_sensitive: false }
    has_secure_password              
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    
    # Returns the hash digest of the given string.
    def User.digest(string)
       cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                     BCrypt::Engine.cost
       BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def User.new_token
       SecureRandom.urlsafe_base64 
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
       self.remember_token = User.new_token
       update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
       BCrypt::Password.new(remember_digest).is_password?(remember_token) 
    end
    
    # Forgets a user.
    def forget
       update_attribute(:remember_digest, nil) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :only_logged_in
  before_action :check_authorization, only: [:show, :update]
  before_action :only_admin, only: [:create, :index, :destroy]
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def index
    @users = User.order(:name).paginate(page: params[:page])
    @newUser = User.new
    @user = User.find_by(id: params[:edit_user]) if params[:edit_user]
  end
  
  def create
    @newUser = User.new(user_params)
    @newUser.password = @newUser.password_confirmation = first_password
    if @newUser.save
      flash[:success] = "New user successfully created"
      redirect_to @newUser
    else
      @users = User.order(:name).paginate(page: params[:page])
      render 'index'
    end
  end
  
  def destroy
    User.find(params[:id]).update_attribute(:deleted, true)
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      @user.reload
      render 'show'
    end
  end
  
  private
    def user_params
      if current_user.admin?
        params.require(:user).permit(:name, :email, :address, :occupation, :password, :password_confirmation, :admin)
      else
        params.require(:user).permit(:name, :email, :address, :occupation, :password, :password_confirmation)
      end
    end
    
    def first_password
      SecureRandom.urlsafe_base64(6)
    end
    
    def check_authorization
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_user_modal.html.erb
<!-- Show modal on load if adding failed -->
<% if @newUser.errors.any? %> 
<script> $(document).ready(function(){ 
    $("#addUserModal").modal("show"); });
</script>
<% end %>

<div id="addUserModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Adding new user</h4>
      </div>
      <%= form_for @newUser do |f| %>
      <div class="modal-body">
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>
            
            <%= f.label :occupation %>
            <%= f.text_field :occupation, class: "form-control" %>
            
            <%= f.check_box :admin %> <%= f.label :admin %>
      </div>
      <div class="modal-footer">
            <%= f.submit "Create user", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_edit_user_modal.html.erb
<!-- Show modal on load if adding failed -->
<% if @user.errors.any? %> 
<script> $(document).ready(function(){ 
    $("#editUserModal").modal("show"); });
</script>
<% end %>

<div id="editUserModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Update user info</h4>
      </div>
      <%= form_for @user do |f| %>
      <div class="modal-body">
        
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>
            
            <%= f.label :occupation %>
            <%= f.text_field :occupation, class: "form-control" %>
            
            <% if current_user.admin? %>
              <%= f.check_box :admin %> <%= f.label :admin %>
            <% end %>
            
      </div>
      <div class="modal-footer">
            <%= f.submit "Save changes", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_user.html.erb
<tr>
    <td><%= link_to user.name, user_path(user) %> <% if user.admin?%><small>(admin)</small> <% end %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td>active</td>
    <td>
        <%= button_to(user, 
                        method: :delete,
                        data: {confirm: "You sure?"},
                        class: "btn btn-danger btn-xs") do %> 
        <i class="fa fa-trash"></i>
                        <% end %>
            <!--            
        <%= button_to(users_path, params: { edit_user: user.id },
                        method: :get,
                        class: "btn btn-primary btn-xs") do %> 
        <i class="fa fa-pencil-square-o"></i>
                        <% end %>
                        
            -->
    </td>
</tr>

app/views/users/_users_table.html.erb
<div class="table-responsive" >
    <table class="table table-hover table-condensed" id="users_table">
    <thead>
      <tr>
        <th data-column-id="Name">Name</th>
        <th data-column-id="Email">Email</th>
        <th data-column-id="Address">Address</th>
        <th data-column-id="Status" data-sortable="false">Status</th>
        <th data-column-id="Actions" data-sortable="false">Actions</th>
      </tr>
    </thead>
    <tbody>
        <%= render @users.where(admin: true) %>
        <%= render @users.where(admin: false) %>
    </tbody>
  </table>
</div>
<%= will_paginate %>

app/views/users/index.html.erb
<%= render 'add_user_modal' %>

<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <i class="fa fa-users" aria-hidden="true"></i> Users <small>(<%= @users.count %>)</small>
    <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#addUserModal">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        Add new user
      </button>
  </div>
  <div class="panel-body"> <%= render 'users_table' %> </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render 'edit_user_modal' %>

<div class="row" >
  <div class="col-lg-4 col-md-4 col-sm-8 col-xs-12">
    <div class="well">
      <%= image_tag 'avatar.png', alt: "avatar", class: "img-circle pull-left", style: "display:inline; width:70px; height:70px;" %>
      <span><%= @user.name %></span><br/>
      <span><%= @user.occupation %></span>
      <div class="clearfix"></div>
      <hr/>
      <button type="button" class="btn btn-info btn-sm" style="display:inline;" data-toggle="modal" data-target="#editUserModal"><i class="fa fa-pencil-square-o"></i> Update info</button>
      <%= button_to(@user, 
                        method: :delete,
                        data: {confirm: "You sure?"},
                        class: "btn btn-danger btn-sm") do %> <i class="fa fa-trash"></i> Delete user<% end %>
    </div>
  </div>
  
  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <div class="panel panel-default panel-table">
      <div class="panel-heading">
        Offers <small>(<%= @user.offers.count %>)</small>
      </div>
      <div class="panel-body"><%= render 'offers/offer_table' %></div>
    </div>
  </div>
</div>

  