config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  get 'projects/show'

  get 'projects/create'

  get 'projects/update'

  get 'projects/destroy'

  get 'dashboard', to: 'timelist#dashboard'

  root 'static_pages#home'
  get '/timelist', to: 'static_pages#timelist'
  get '/drivebook', to: 'static_pages#drivebook'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users, only: [:show, :index, :destroy, :create, :update]
  resources :clients, only: [:show, :index, :destroy, :create, :update]
  resources :projects, only: [:show, :index, :destroy, :create, :update]
  resources :offers, only: [:show, :index, :destroy, :create, :update]
  resources :offer_reminders, only: [:create, :destroy, :update]
  resources :contact_people, only: [:create, :destroy, :update]
  resources :notifications, only: [:show]
  resources :timelist_records, only: [:create, :destroy, :update], controller: :timelist
  resources :no_work_records, only: [:create, :destroy, :update]
  resources :work_records, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :user
  has_many :offers
  
  validates :name, presence: true
  validates :client_id, presence: true
  
  def should_be_updated?
    self.address.blank? || self.csnumber.blank? || self.status.blank? 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :only_logged_in
  before_action :only_admin
  
  def index
    @projects = Project.paginate(page: params[:page])
    @newProject = Project.new
    @clients = Client.order(name: :asc)
  end

  def show
    @project = Project.find_by(id: params[:id])
    redirect_to projects_path unless Project.exists?(@project)
    @newOffer = Offer.new
    @admins = User.where(admin: true)
    
    
    default_start = (Date.today + 7.hours)
    default_end = (Date.today + 15.hours)
    timelist_params
    @newRecord = WorkRecord.new(time_start: default_start, time_end: default_end)
    @records = TimelistRecord.timelist(@from, @to, @user, params[:id], false, @notconf).paginate(page: params[:page], per_page: 15).order(time_start: :desc, created_at: :desc)
  end

  def create
    @clients = Client.order(name: :asc)
    @projects = Project.paginate(page: params[:page])
    @newProject = Project.new(project_params)
    if @newProject.save
      flash[:success] = "Project created!"
      redirect_to @newProject
    else
      render 'index'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project updated"
      redirect_to @project
    else
      @project.reload
      render 'show'
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.update_attribute(:deleted, true)
    project.offers.update_all(deleted: true)
    flash[:success] = "Project deleted"
    redirect_to project.client
  end
  
  private

    def timelist_params
      if request.GET[:from].blank?
        @from = session[:date_from].try(:to_datetime) || Date.today - 2.weeks
      else
        @from = request.GET[:from].to_datetime
      end
      if request.GET[:to].blank?
        @to = session[:date_to].try(:to_datetime) || Date.today + 23.hours + 59.minutes
      else
        @to = request.GET[:to].to_datetime + 23.hours + 59.minutes
      end
      if request.GET[:notconf].blank?
        @notconf = false
      else
        @notconf = true
      end
      
      if request.GET['user'].blank?
        @user = session[:timelist_user] || 'all'
      else
        @user = request.GET['user']
      end

    end
    
    def project_params
      params.require(:project).permit(:name, :user_id, :csnumber, :client_id, :address, :status)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_project_modal.html.erb
<!-- Show modal on load if adding failed -->
<% if @newProject.errors.any? %> 
<script> $(document).ready(function(){ 
    $("#addProjectModal").modal("show"); });
</script>
<% end %>

<div id="addProjectModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Adding new project</h4>
      </div>
      <%= form_for @newProject do |f| %>
      <div class="modal-body">
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <% if @client %>
            <%= f.hidden_field :client_id, value: @client.id %>
            <% else %>
            <%= f.label :client %>
            <%= f.select :client_id, 
                         @clients.map{ |c| [c.name, c.id] }, 
                         {prompt: 'Select'}, {class: "form-control"} %>
            <% end %>
            
             <%= f.label :user, "Responsible person:" %>
            <%= f.select :user_id,
                         User.where(admin: true).map{ |c| [c.name, c.id] }, 
                         {prompt: 'Select'}, {class: "form-control"} %>
                         
            <%= f.label :csnumber %>
            <%= f.text_field :csnumber, class: "form-control" %>
            
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>
            
            <%= f.label :status %>
            <%= f.select :status, ["pending", "in progress", "finished"],
                                  { prompt: 'Select', selected: "pending" },
                                  { class: "form-control" } %>
            
      </div>
      <div class="modal-footer">
            <%= f.submit "Create project", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/projects/_edit_project_modal.html.erb
<!-- Show modal on load if adding failed -->
<% if @project.errors.any? %> 
<script> $(document).ready(function(){ 
    $("#editProjectModal").modal("show"); });
</script>
<% end %>

<div id="editProjectModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Update project info</h4>
      </div>
      <%= form_for @project do |f| %>
      <div class="modal-body">
        
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :csnumber %>
            <%= f.text_field :csnumber, class: "form-control" %>
            
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>
            
            <%= f.label :status %>
            <%= f.select :status, ["pending", "in progress", "finished"],
                                  { prompt: 'Select' },
                                  { class: "form-control" } %>
            
      </div>
      <div class="modal-footer">
            <%= f.submit "Save changes", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/projects/_project.html.erb
<tr id="<%= project.id %>">
    <td><%= link_to project.name, project %></td>
    <% if !@client #do not show this column on client page %>
    <td><%= link_to project.client.name, project.client %></td>
    <% end %>
    <td><%= project.csnumber %></td>
    <td><%= project.address %></td>
    <td><%= project.status %></td>
</tr>

app/views/projects/_projects_table.html.erb
<div class="table-responsive" >
    <table class="table table-hover table-condensed" id="clients_table">
    <thead>
      <tr>
        <th data-column-id="Name">Name</th>
        <% if !@client #do not show this column on client page %> 
        <th data-column-id="Client">Client</th>
        <% end %>
        <th data-column-id="CSNumber">CSNumber</th>
        <th data-column-id="Address">Address</th>
        <th data-column-id="Status" data-sortable="false">Status</th>
      </tr>
    </thead>
    <tbody>
        <%= render @projects %>
    </tbody>
  </table>
</div>

<%= will_paginate @projects %>

app/views/projects/index.html.erb
<%= render 'add_project_modal' %>

<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <i class="fa fa-cubes" aria-hidden="true"></i> Projects <small>(<%= @projects.count %>)</small>
    <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#addProjectModal">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        Add new project
      </button>
  </div>
  <div class="panel-body"> <%= render 'projects_table' %> </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<%= render 'edit_project_modal' %>
<%= render 'offers/add_offer_modal' %>


<div class="row" >
  <div class="col-lg-4 col-md-4 col-sm-8 col-xs-12">
    <div class="well">
      <h2><%= @project.name %></h2>
      <span><%= @project.address %></span><br/>
      <span class="pull-right"><%= link_to @project.client.name, client_path(@project.client) %></span>
      <div class="clearfix"></div>
      <hr style="margin-top: 3px;"/>
      <button type="button" class="btn btn-info btn-sm" style="display:inline;" data-toggle="modal" data-target="#editProjectModal"><i class="fa fa-pencil-square-o"></i> Update info</button>
      <%= button_to(@project, 
                        method: :delete,
                        data: {confirm: "You sure?"},
                        class: "btn btn-danger btn-sm") do %> <i class="fa fa-trash"></i> Delete project<% end %>
    </div>
    <% if @project.should_be_updated? %>
      <div class="alert alert-warning reminder">
        <strong><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></strong>
        <span>Project info is incomplete</span>
      </div>
    <% end %>
    
  </div>
  
  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <div class="panel panel-default panel-table">
      <div class="panel-heading">
        <i class="fa fa-folder-open" aria-hidden="true"></i> Offers <small>(<%= @project.offers.count %>)</small>
        <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#addOfferModal">
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
            Add new offer
          </button>
      </div>
      <div class="panel-body"> <%= render 'offers/offer_table' %> </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <%= render 'timelist/record_form', show_user: true, show_project: false, default_project: @project %>
    </div>
    
    <div class="col-sm-9">
        <%= render 'timelist/timelist', show_user: true, show_project: false, projects_options: [["All", 'all']] %>
    </div>
</div>